# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('sex', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='\u7537', max_length=32)),
                ('ac_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ac_time'],
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
    ]
