# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20180917_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPwdTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '\u5bc6\u7801\u4fdd\u5b58\u6d4b\u8bd5\u8868',
                'verbose_name_plural': '\u5bc6\u7801\u4fdd\u5b58\u6d4b\u8bd5\u8868',
            },
        ),
        migrations.AlterModelOptions(
            name='dept',
            options={'verbose_name': '\u90e8\u95e8', 'verbose_name_plural': '\u90e8\u95e8\u8868'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '\u5458\u5de5\u4fe1\u606f', 'verbose_name_plural': '\u5458\u5de5\u4fe1\u606f\u8868'},
        ),
        migrations.AlterField(
            model_name='dept',
            name='name',
            field=models.CharField(max_length=32, verbose_name='\u90e8\u95e8\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.PositiveSmallIntegerField(default='35', verbose_name='\u5e74\u9f84'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Dept', verbose_name='\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '\u7537\u6027'), (2, '\u5973\u6027')], default='1', verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='\u4f8b\uff1a\u5f20\u4e092', max_length=32, verbose_name='\u5458\u5de5\u59d3\u540d'),
        ),
    ]
